# Generated by Django 5.1.14 on 2026-02-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscheck',
            options={'ordering': ['-created_at']},
        ),
    ]
