# Generated by Django 5.1.14 on 2026-02-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_alter_newscheck_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscheck',
            name='category',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
